### ISSUE TITLE
アカウント消したのにデータベースからデータ消えてない・友達関係も消えて欲しい

### ISSUE THREAD

**Issue by MasudaHinata** [MasudaHinata/pppppp#139]

**Comment by masakazozaki** [comment]
authとFirestoreのUserDataは別物だからauthでdeleteしただけじゃUserDataは消えることはない。
deleteしたいと思ったら

1. 削除したいユーザのフレンドリストを取得
2. フレンド全員のfriendListから削除したいユーザのIDを削除
3. 削除したいユーザのUserDataを削除
4. authのuserを削除 

をやる必要があるね
